name: test-core-ivy-cron
on:
  push:
  pull_request:
      types: [ labeled, opened, synchronize, reopened, review_requested ]
permissions:
  actions: read
jobs:
   run-nightly-tests:
     if: ${{contains(github.event.pull_request.labels.*.name, 'Bug') }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Download artifact
         uses: dawidd6/action-download-artifact@v2
         with:
           github_token: ${{secrets.GITHUB_TOKEN}}
           workflow: test-ivy-core-cron.yml
           workflow_conclusion: ""
           search_artifacts: true
           name: hypothesis_zip
           path: |
             ivy/.hypothesis/
         continue-on-error: true

       - name: Unzip Hypothesis Examples
         id: unzip
         run: |
           cd ivy/.hypothesis
           unzip examples.zip
           rm examples.zip
         continue-on-error: true

       - name: Create Hypothesis Directory
         if: steps.unzip.outcome != 'success'
         run: |
           cd ivy
           mkdir -p .hypothesis
           cd .hypothesis
           mkdir -p examples
         continue-on-error: true

       - name: Run Functional-Core Tests
         shell: bash
         id: tests
         run: |
           cd ivy
           echo "BACKEND=None" >> $GITHUB_ENV
           echo "SUBMODULE=None" >> $GITHUB_ENV
           python run_tests_CLI/run_ivy_core_test.py ${{ github.run_number }}
           echo ${{ github.workflow }} 
           echo ${{ env.BACKEND }} 
           echo ${{ env.SUBMODULE }}
         continue-on-error: true

       - name: Zip Hypothesis Examples
         run: |
           cd ivy/.hypothesis
           zip -r examples.zip examples
         continue-on-error: true

       - name: Upload hypothesis
         uses: actions/upload-artifact@v3
         with:
           name: hypothesis_zip
           path: |
             ivy/.hypothesis/examples.zip
         continue-on-error: true

       - name: Update Dashboard
         run: |
             echo ${{ github.workflow }} ${{ env.BACKEND }} ${{ matrix.SUBMODULE }}
       - name: Check on failures
         if: steps.tests.outcome != 'success'
         run: exit 1
